formset/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from formsetapp.views import person_formset_view, PersonList, PersonEdit, PersonDelete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^add-person/$', person_formset_view, name='add-person'),
    # url(r'^list-people/$', PersonList.as_view(), name='list-people'),
    # url(r'^edit-person/(?P<pk>\d+)/$', PersonEdit.as_view(), name='edit-person'),
    # url(r'^delete-person/(?P<pk>\d+)/$', PersonDelete.as_view(), name='delete-person')
    url(r'^person/', include('formsetapp.urls', namespace='person'))
]

formsetapp/urls.py
from django.conf.urls import url
from formsetapp.views import person_formset_view, PersonList, PersonEdit, PersonDelete, PersonDetail

urlpatterns = [
  url(r'^add/$', person_formset_view, name='add'),
  url(r'^list/$', PersonList.as_view(), name='list'),
  url(r'^edit/(?P<pk>\d+)/$', PersonEdit.as_view(), name='edit'),
  url(r'^detail/(?P<pk>\d+)/$', PersonDetail.as_view(), name='detail'),
  url(r'^delete/(?P<pk>\d+)/$', PersonDelete.as_view(), name='delete')
]

formsetapp/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
   name = models.CharField(max_length=100)

formsetapp/forms.py
from django import forms
from django.forms.formsets import BaseFormSet
from .models import Person

class PersonForm(forms.ModelForm):
  name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Name',}), required=False)

  class Meta:
    model = Person
    fields = ('name',)

formsetapp/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.forms.formsets import formset_factory
from django.contrib import messages
from .forms import PersonForm
from .models import Person
from django.views.generic import ListView, UpdateView, DeleteView, DetailView

def person_formset_view(request):

  PersonFormset = formset_factory(PersonForm)

  if request.method == 'POST':
    person_formset = PersonFormset(request.POST)

    if person_formset.is_valid():

      new_people = []

      for  person_form in person_formset:
        name = person_form.cleaned_data.get('name')

        if name:
          new_people.append(Person(name=name))

      try:
        Person.objects.bulk_create(new_people)

        # And notify our users that it worked
        messages.success(request, 'You have updated your people.')
        return redirect(reverse_lazy('person:list'))

      except: #If the transaction failed
        messages.error(request, 'There was an error saving your people.')
        return redirect(reverse_lazy('person:add'))

  else:
    person_formset = PersonFormset()

  context = {
    'person_formset': person_formset 
  }

  return render(request, 'formsetapp/add_person.html', context)

class PersonList(ListView):
  model = Person
  template_name = 'formsetapp/list_people.html'

class PersonEdit(UpdateView):
  model = Person
  form_class = PersonForm
  template_name = 'formsetapp/edit_person.html'
  def get_success_url(self):
    return reverse('person:detail', kwargs={'pk' : self.object.pk})

class PersonDelete(DeleteView):
  model = Person
  success_url = reverse_lazy('person:list')

class PersonDetail(DetailView):
  model = Person
  template_name = 'formsetapp/detail_person.html'

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">

  {% block extrastatic %}
  {% endblock %}

  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

  {% block navbar %}
    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                  <nav class="navbar navbar-default">
                      <div class="container-fluid">
                          <div class="navbar-header">
                            <a class="navbar-brand" href="#">Home</a>
                          </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          <ul class="nav navbar-nav">
                              <li class="dropdown">
                                <a href="{% url 'person:list' %}" role="button" aria-expanded="false">People List</a>
                              </li>
                          </ul>
                          <ul class="nav navbar-nav navbar-right">
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                </ul>
                              </li>
                          </ul>
                        </div>
                    </div>
                </nav>
            </div>
            </div>
        </div>
    </div>
  {% endblock %}


  {% block content %}
  <h4>  Bloque de contenido   </h4>
  {% endblock %}


  {% block footer %}
  {% endblock%}
</div>
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  {% block extrajs %}
  {% endblock %}


</body>
</html>

templates/formsetapp/add_person.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Add people</h1>
    {% if messages %}
      {% for message in messages %}
          <p>{{ message }}</p>
      {% endfor %}
    {% endif %}
    <form method="post">
      {% csrf_token %}
      {{ person_formset.management_form }}
      {% for person_form in person_formset %}
          <div class="person-formset">
              {{ person_form|crispy }}
          </div>
      {% endfor %}
      <input style='display:block; margin-top:15px' type="submit" value="save">
    </form>
{% endblock %}

{% block extrajs %}
  <script src="{% static 'js/django-dynamic-formset/src/jquery.formset.js' %}"></script>
  <script>
    $('.person-formset').formset({
        addText: '+ add person',
        deleteText: 'remove',
        deleteCssClass: 'btn btn-danger delete-row',
        addCssClass: 'btn btn-primary'
    });
  </script>
{% endblock %}

templates/formsetapp/detail_person.html
{% extends 'base/base.html' %}

{% block content %}
<h1>{{ object.name|capfirst }}</h1>
<a href="{% url 'person:edit' object.id %}">Editar</a>
<a style='color: #cb2353' href="{% url 'person:delete' object.id %}">Eliminar</a>
{% endblock %}

templates/formsetapp/edit_person.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Edit Person</h1>
<form method='post'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="save">
</form>
{% endblock %}

templates/formsetapp/list_people.html
{% extends 'base/base.html' %}

{% block content %}

<a class='btn btn-primary' href="{% url 'person:add' %}">+ Add People</a>
{% if object_list %}
  <ul style='list-style-type: none; padding: 0'>
  {% for person in object_list %}
    <li class='list-element'>
      <div style='float: left'>
        <strong><a href="{% url 'person:detail' person.id %}">{{ person.name|capfirst }}</a></strong>
      </div>
      <div style='float: right'>
        <a href="{% url 'person:edit' person.id %}">Editar</a>
        <a style='color: #cb2353' href="{% url 'person:delete' person.id %}">Eliminar</a>
      </div>
    </li>
  {% endfor %}
  </ul>
  
{% else %}
  <h1>Nothing here</h1>
{% endif %}

{% endblock %}

templates/formsetapp/person_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
	<form method="post">

		{% csrf_token %}
		<h3>Desea eliminar el registro de {{ object.name }}?</h3>
		<button class="btn btn-danger" type='submit'>Si</button>
		<a class='btn btn-default' href="{% url 'person:list' %}">Cancelar</a>
	</form>
{% endblock %}